In [11]:
from utils import utils, check
from algorithms.brute_force import BruteForce
from algorithms.dict_version.brute_force import BruteForce as DictBruteForce
from algorithms.barman import Barman
from algorithms.garg import GargAlgorithm
from algorithms.dict_version.barman import Barman as DictBarman
from algorithms.envy_cycle import EnvyCycleElimination
from algorithms.generalized_adjusted_winner import GeneralizedAdjustedWinner
from utils.check import Checker
from algorithms.minmaxenvy_trade import MinimaxTrade
from algorithms.seq_min_envy import SeqMinEnvy
from algorithms import mnw 
from utils import utils


import numpy as np

# Usage example of the checker class

## Generate random valuation for two agents

In [12]:
n = 2
m = 6
valuation_range = np.array([1, 21])
valuation = utils.randint_valuation(n, m, valuation_range)
print(f"Valuation: \n{valuation}\n")

Valuation: 
[[ 1  1 11 14 13 10]
 [14  9  4  4  2 17]]



In [13]:
genaw = GeneralizedAdjustedWinner(valuation)
allocation = genaw.get_allocation()

for allocation in allocation:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="gen_adjusted_winner")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n") 

Current allocation: 
[[0 0 1 1 1 1]
 [1 1 0 0 0 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 1 1 0]
 [1 1 1 0 0 1]]

Is resource monotonicity: True



In [14]:
minimax = MinimaxTrade(len(valuation), len(valuation[0]), valuation)
allocation = minimax.minimax_trade()

print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="bf")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")


Current allocation: 
[[0 0 1 1 1 0]
 [1 1 0 0 0 1]]

Is resource monotonicity: True



## Generate random valuation

In [15]:
n = 4
m = 6
valuation_range = np.array([1, 21])
valuation = utils.randint_valuation(n, m, valuation_range)
print(f"Valuation: \n{valuation}\n")

Valuation: 
[[3 8 4 6 9 5]
 [7 4 8 7 2 0]
 [2 7 4 7 1 6]
 [9 4 8 2 1 7]]



In [16]:
allocations = mnw.maximize_nash_welfare_bruteforce(n, m, valuation)

for allocation in allocations:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="mnw")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 0 0 0 1]]



c:\Users\Admin\github\indivisible_goods_allocation\utils\check.py:770: RuntimeWarning: divide by zero encountered in log
  log_weights = np.log(weights)


Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: False



In [17]:
barman = Barman(n, m, valuation)
allocation, price = barman.run_algorithm()
print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="barman")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True



In [18]:
garg = GargAlgorithm(n, m, valuation)
allocation, price = garg.run_algorithm()
print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="garg")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True



In [19]:
bf = BruteForce(n, m, valuation)
allocations = bf.compute_ef1_and_po_allocations()
for allocation in allocations:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="bf")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [1 0 1 0 0 1]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 1 0 0 0]
 [0 1 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 0 1 0 0]
 [0 1 0 0 0 1]
 [1 0 1 0 0 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 1 1 0 0]
 [0 1 0 0 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True

Current allocation: 
[[0 0 0 0 1 0]
 [0 0 1 1 0 0]
 [0 1 0 0 0 1]
 [1 0 0 0 0 0]]

Is resource monotonicity: True

Current allocation: 
[[0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True

Current allocation: 
[[0 1 0 0 1 0]
 [0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [1 0 1 0 0 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 1 1]
 [0 0 0 1 0 0]
 [0 1 0 0 0 0]
 [1 0 1 0 0 0]]

Is resource monotonicity: False

Current allocation: 
[[0 1 0 0 1 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 1]
 [1 0 0 0 

In [20]:
EnvyCycle = EnvyCycleElimination(n, m, valuation)
allocation = EnvyCycle.envy_cycle_elimination()

print(f"Current allocation: \n{allocation}\n")

Current allocation: 
[[0 0 0 1 1 0]
 [0 0 1 0 0 1]
 [0 1 0 0 0 0]
 [1 0 0 0 0 0]]

