In [70]:
from utils import utils, check
from algorithms.brute_force import BruteForce
from algorithms.dict_version.brute_force import BruteForce as DictBruteForce
from algorithms.barman import Barman
from algorithms.garg import GargAlgorithm
from algorithms.dict_version.barman import Barman as DictBarman
from algorithms.envy_cycle import EnvyCycleElimination
from algorithms.generalized_adjusted_winner import GeneralizedAdjustedWinner
from utils.check import Checker
from algorithms.minmaxenvy_trade import MinimaxTrade
from algorithms.seq_min_envy import SeqMinEnvy
from algorithms import mnw 
from utils import utils


import numpy as np

# Usage example of the checker class

## Generate random valuation for two agents

In [71]:
n = 2
m = 6
valuation_range = np.array([1, 21])
valuation = utils.randint_valuation(n, m, valuation_range)
print(f"Valuation: \n{valuation}\n")

Valuation: 
[[10 20  2  2  1 16]
 [ 3 15  4 10 17 10]]



In [72]:
genaw = GeneralizedAdjustedWinner(valuation)
allocation = genaw.get_allocation()

for allocation in allocation:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="gen_adjusted_winner")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n") 

Current allocation: 
[[1 1 1 0 0 1]
 [0 0 0 1 1 0]]

Is resource monotonicity: True

Current allocation: 
[[1 0 0 0 0 1]
 [0 1 1 1 1 0]]

Is resource monotonicity: True



In [73]:
minimax = MinimaxTrade(len(valuation), len(valuation[0]), valuation)
allocation = minimax.minimax_trade()

print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="bf")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")


Current allocation: 
[[0 1 0 0 0 1]
 [1 0 1 1 1 0]]

Is resource monotonicity: True



## Generate random valuation

In [74]:
n = 4
m = 6
valuation_range = np.array([1, 21])
valuation = utils.random_uniform_valuation(n, m)
print(f"Valuation: \n{valuation}\n")

Valuation: 
[[0.88054812 0.27761918 0.73356968 0.42473049 0.00289679 0.5524786 ]
 [0.27149061 0.49224247 0.07841474 0.10275673 0.86724044 0.63448365]
 [0.8452979  0.53737006 0.89894661 0.88334163 0.73569832 0.05179833]
 [0.91751434 0.4902376  0.43080158 0.485536   0.87662266 0.24502286]]



In [75]:
allocations = mnw.maximize_nash_welfare(n, m, valuation)

for allocation in allocations:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="mnw")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[1 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 0 1 0]]

Is resource monotonicity: False



In [76]:
barman = Barman(n, m, valuation)
allocation, price = barman.run_algorithm()
print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="barman")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[1 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 0 1 0]]

Is resource monotonicity: False



In [77]:
garg = GargAlgorithm(n, m, valuation)
allocation, price = garg.run_algorithm()
print(f"Current allocation: \n{allocation}\n")
checker = Checker(n, m, valuation, allocation, method="garg")
is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
print(f"Is resource monotonicity: {is_rm}\n")

Current allocation: 
[[1 0 0 0 0 0]
 [0 1 0 0 0 1]
 [0 0 1 1 0 0]
 [0 0 0 0 1 0]]

Is resource monotonicity: False



In [78]:
bf = BruteForce(n, m, valuation)
allocations = bf.compute_ef1_and_po_allocations()
for allocation in allocations:
    print(f"Current allocation: \n{allocation}\n")
    checker = Checker(n, m, valuation, allocation, method="bf")
    is_rm, removed_items, breach_allocation = checker.check_resource_monotonicity()
    print(f"Is resource monotonicity: {is_rm}\n")

4
Current allocation: 
[[1 0 0 0 0 0]
 [0 0 0 0 1 0]
 [0 0 1 0 0 1]
 [0 1 0 1 0 0]]

Is resource monotonicity: True

Current allocation: 
[[1 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 1 1 0 0]
 [0 1 0 0 1 0]]

Is resource monotonicity: True

Current allocation: 
[[0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 1 0 1 0 0]
 [1 0 0 0 0 1]]

Is resource monotonicity: True

Current allocation: 
[[0 0 1 0 0 0]
 [0 0 0 0 1 0]
 [0 0 0 1 0 1]
 [1 1 0 0 0 0]]

Is resource monotonicity: True

Current allocation: 
[[0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 1 0 1 0 0]
 [1 0 0 0 1 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 1 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 1 1 0]
 [1 1 0 0 0 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 1 0 0]
 [0 0 0 0 0 1]
 [0 1 1 0 0 0]
 [1 0 0 0 1 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 0 1]
 [0 1 0 0 0 0]
 [0 0 1 1 0 0]
 [1 0 0 0 1 0]]

Is resource monotonicity: False

Current allocation: 
[[0 0 0 0 0 1]
 [0 0 0 0 1 0]
 [0 0 1 1 0 0]
 [1 1 0 

KeyboardInterrupt: 

In [ ]:
EnvyCycle = EnvyCycleElimination(n, m, valuation)
allocation = EnvyCycle.envy_cycle_elimination()

print(EnvyCycle.A)

AttributeError: 'EnvyCycleElimination' object has no attribute 'A'